export const api = {
    addAttachment: '/attachment/upload',
    getAttachment: '/attachment',
    secondary: "/secondary",

    login: '/auth/login',
    userMe: '/auth/me',
    registerUser: '/auth/register',
    user: '/user',
    userl: '/user/one',
    user_debt: '/user/debt',
    user_pass: '/user/password',
    client: '/user/select/client',
    worker: '/user/select/worker',
    finalRegisterUser: '/auth/finalRegister',
    activate: '/auth/activate/',

    payment : "/payment",
    pay_cash : "/pay-cash",

    country : '/country',
    region : '/region',
    district : '/district',
    category : '/category',
    company : '/company',
    brand: '/brand',
    expense: '/expense',
    car: '/car',
    car_affair: '/car-affair',
    affair: '/affair',
    order_affair: '/order-affair',
    accept_order_affair: '/order-affair/accept',
    ready_order_affair: '/order-affair/ready',
    bank: '/bank',
    bank_affair: 'bank-affair',
    accessory : "/accessory",
    accessory_select : "/accessory/select",
    accessory_income : "/accessory-affair/income",
    accessory_shipment : "/accessory-affair/shipment",
    order_salary : "/order-salary",

    template : '/productTemplate',
    template_income : '/template/income-select',
    template_shipment : '/productTemplate/shipment-select',
    shipment_products : '/template/shipment-select',

    product : '/product',
    new_operations : '/product/new-operations',
    income : '/income',
    shipment : '/shipment',
    accept_shipment : '/product/accept/shipment',


    variation : '/variation',
    element  : '/element',
    role : '/auth/roles',

    glass_dashboard: '/dashboard/glass',
    affair_dashboard: '/dashboard/affair',
    bank_dashboard: '/dashboard/bank',
    salary_dashboard: '/dashboard/salary',
    accessory_dashboard: '/dashboard/accessory',
    car_dashboard: '/dashboard/car',
    expense_dashboard: '/dashboard/expense',
    pay_cash_dashboard: '/dashboard/pay-cash',
    payment_dashboard: '/dashboard/payment',


    operation : "/operation",
    course : "/course",
    section: "/section",
    section_member: "/affair/member",

    sms: "/sms",
    order: "/order",
};