export const REQUEST_START = 'REQUEST_START';
export const REQUEST_ERROR = 'REQUEST_ERROR';

export const REQUEST_GET_COURSE_ONE_SUCCESS = 'REQUEST_GET_COURSE_ONE_SUCCESS';
export const REQUEST_GET_AFFAIR_ONE_SUCCESS = 'REQUEST_GET_AFFAIR_ONE_SUCCESS';

export const REQUEST_GET_PAYMENT_SUCCESS = 'REQUEST_GET_PAYMENT_SUCCESS';
export const REQUEST_GET_PAYMENT_SEARCH_SUCCESS = 'REQUEST_GET_PAYMENT_SEARCH_SUCCESS';

export const REQUEST_GET_PAY_CASH_SUCCESS = 'REQUEST_GET_PAY_CASH_SUCCESS';
export const REQUEST_GET_PAY_CASH_SEARCH_SUCCESS = 'REQUEST_GET_PAY_CASH_SEARCH_SUCCESS';


export const REQUEST_GET_USER_SUCCESS = 'REQUEST_GET_USER_SUCCESS';
export const REQUEST_GET_USERL_ONE_SUCCESS = 'REQUEST_GET_USERL_ONE_SUCCESS';
export const REQUEST_GET_USER_DEBT_SUCCESS = 'REQUEST_GET_USER_DEBT_SUCCESS';
export const REQUEST_GET_USER_SEARCH_SUCCESS = 'REQUEST_GET_USER_SEARCH_SUCCESS';


export const REQUEST_GET_ORDER_SALARY_SUCCESS = 'REQUEST_GET_ORDER_SALARY_SUCCESS';
export const REQUEST_GET_ORDER_SALARY_SEARCH_SUCCESS = 'REQUEST_GET_ORDER_SALARY_SEARCH_SUCCESS';

export const REQUEST_GET_CLIENT_SUCCESS = 'REQUEST_GET_CLIENT_SUCCESS';
export const REQUEST_GET_WORKER_SUCCESS = 'REQUEST_GET_WORKER_SUCCESS';

export const REQUEST_GET_EXPENSE_SUCCESS = 'REQUEST_GET_EXPENSE_SUCCESS';
export const REQUEST_GET_EXPENSE_SEARCH_SUCCESS = 'REQUEST_GET_EXPENSE_SEARCH_SUCCESS';

export const REQUEST_GET_CAR_SUCCESS = 'REQUEST_GET_CAR_SUCCESS';
export const REQUEST_GET_CAR_SEARCH_SUCCESS = 'REQUEST_GET_CAR_SEARCH_SUCCESS';
export const REQUEST_GET_CAR_AFFAIR_SUCCESS = 'REQUEST_GET_CAR_AFFAIR_SUCCESS';
export const REQUEST_GET_CAR_AFFAIR_SEARCH_SUCCESS = 'REQUEST_GET_CAR_AFFAIR_SEARCH_SUCCESS';

export const REQUEST_GET_AFFAIR_SUCCESS = 'REQUEST_GET_AFFAIR_SUCCESS';
export const REQUEST_GET_AFFAIR_SEARCH_SUCCESS = 'REQUEST_GET_AFFAIR_SEARCH_SUCCESS';
export const REQUEST_GET_ORDER_AFFAIR_SUCCESS = 'REQUEST_GET_ORDER_AFFAIR_SUCCESS';
export const REQUEST_GET_ORDER_AFFAIR_SEARCH_SUCCESS = 'REQUEST_GET_ORDER_AFFAIR_SEARCH_SUCCESS';

export const REQUEST_GET_BANK_SUCCESS = 'REQUEST_GET_BANK_SUCCESS';
export const REQUEST_GET_BANK_SEARCH_SUCCESS = 'REQUEST_GET_BANK_SEARCH_SUCCESS';
export const REQUEST_GET_BANK_AFFAIR_SUCCESS = 'REQUEST_GET_BANK_AFFAIR_SUCCESS';
export const REQUEST_GET_BANK_AFFAIR_SEARCH_SUCCESS = 'REQUEST_GET_BANK_AFFAIR_SEARCH_SUCCESS';

export const REQUEST_GET_ACCESSORY_SUCCESS = 'REQUEST_GET_ACCESSORY_SUCCESS';
export const REQUEST_GET_ACCESSORY_SELECT_SUCCESS = 'REQUEST_GET_ACCESSORY_SELECT_SUCCESS';
export const REQUEST_GET_ACCESSORY_SEARCH_SUCCESS = 'REQUEST_GET_ACCESSORY_SEARCH_SUCCESS';

export const REQUEST_GET_ACCESSORY_INCOME_SUCCESS = 'REQUEST_GET_ACCESSORY_INCOME_SUCCESS';
export const REQUEST_GET_ACCESSORY_INCOME_SEARCH_SUCCESS = 'REQUEST_GET_ACCESSORY_INCOME_SEARCH_SUCCESS';

export const REQUEST_GET_ACCESSORY_SHIPMENT_SUCCESS = 'REQUEST_GET_ACCESSORY_SHIPMENT_SUCCESS';
export const REQUEST_GET_ACCESSORY_SHIPMENT_SEARCH_SUCCESS = 'REQUEST_GET_ACCESSORY_SHIPMENT_SEARCH_SUCCESS';


export const REQUEST_GET_BRAND_SUCCESS = 'REQUEST_GET_BRAND_SUCCESS';
export const REQUEST_GET_BRAND_SEARCH_SUCCESS = 'REQUEST_GET_BRAND_SEARCH_SUCCESS';

export const REQUEST_GET_CATEGORY_SUCCESS = 'REQUEST_GET_CATEGORY_SUCCESS';
export const REQUEST_GET_CATEGORY_SEARCH_SUCCESS = 'REQUEST_GET_CATEGORY_SEARCH_SUCCESS';

export const REQUEST_GET_TEMPLATE_SUCCESS = 'REQUEST_GET_TEMPLATE_SUCCESS';
export const REQUEST_GET_TEMPLATE_SEARCH_SUCCESS = 'REQUEST_GET_TEMPLATE_SEARCH_SUCCESS';

export const REQUEST_GET_INCOME_SUCCESS = 'REQUEST_GET_INCOME_SUCCESS';
export const REQUEST_GET_INCOME_SEARCH_SUCCESS = 'REQUEST_GET_INCOME_SEARCH_SUCCESS';

export const REQUEST_GET_SHIPMENT_SUCCESS = 'REQUEST_GET_SHIPMENT_SUCCESS';
export const REQUEST_GET_SHIPMENT_SEARCH_SUCCESS = 'REQUEST_GET_SHIPMENT_SEARCH_SUCCESS';

export const REQUEST_GET_TEMPLATE_INCOME_SUCCESS = 'REQUEST_GET_TEMPLATE_INCOME_SUCCESS';
export const REQUEST_GET_TEMPLATE_SHIPMENT_SUCCESS = 'REQUEST_GET_TEMPLATE_SHIPMENT_SUCCESS';
export const REQUEST_GET_SHIPMENT_PRODUCTS_SUCCESS = 'REQUEST_GET_SHIPMENT_PRODUCTS_SUCCESS';

export const REQUEST_GET_PRODUCT_SUCCESS = 'REQUEST_GET_PRODUCT_SUCCESS';
export const REQUEST_GET_PRODUCT_SEARCH_SUCCESS = 'REQUEST_GET_PRODUCT_SEARCH_SUCCESS';
export const REQUEST_GET_ROLE_SUCCESS = 'REQUEST_GET_ROLE_SUCCESS';

export const REQUEST_GET_GLASS_DASHBOARD_SUCCESS = 'REQUEST_GET_GLASS_DASHBOARD_SUCCESS';
export const REQUEST_GET_AFFAIR_DASHBOARD_SUCCESS = 'REQUEST_GET_AFFAIR_DASHBOARD_SUCCESS';
export const REQUEST_GET_BANK_DASHBOARD_SUCCESS = 'REQUEST_GET_BANK_DASHBOARD_SUCCESS';
export const REQUEST_GET_SALARY_DASHBOARD_SUCCESS = 'REQUEST_GET_SALARY_DASHBOARD_SUCCESS';
export const REQUEST_GET_ACCESSORY_DASHBOARD_SUCCESS = 'REQUEST_GET_ACCESSORY_DASHBOARD_SUCCESS';
export const REQUEST_GET_CAR_DASHBOARD_SUCCESS = 'REQUEST_GET_CAR_DASHBOARD_SUCCESS';
export const REQUEST_GET_EXPENSE_DASHBOARD_SUCCESS = 'REQUEST_GET_EXPENSE_DASHBOARD_SUCCESS';
export const REQUEST_GET_PAY_CASH_DASHBOARD_SUCCESS = 'REQUEST_GET_PAY_CASH_DASHBOARD_SUCCESS';
export const REQUEST_GET_PAYMENT_DASHBOARD_SUCCESS = 'REQUEST_GET_PAYMENT_DASHBOARD_SUCCESS';


// Single object Start
export const REQUEST_GET_ORDER_AFFAIR_ONE_SUCCESS = "REQUEST_GET_ORDER_AFFAIR_ONE_SUCCESS";
export const REQUEST_GET_INCOME_ONE_SUCCESS = "REQUEST_GET_INCOME_ONE_SUCCESS";
export const REQUEST_GET_SHIPMENT_ONE_SUCCESS = "REQUEST_GET_SHIPMENT_ONE_SUCCESS";
export const REQUEST_GET_TEMPLATE_ONE_SUCCESS = "REQUEST_GET_TEMPLATE_ONE_SUCCESS";
export const REQUEST_GET_ACCESSORY_INCOME_ONE_SUCCESS = "REQUEST_GET_ACCESSORY_INCOME_ONE_SUCCESS";
export const REQUEST_GET_ACCESSORY_SHIPMENT_ONE_SUCCESS = "REQUEST_GET_ACCESSORY_SHIPMENT_ONE_SUCCESS";
// Single object End


export const REQUEST_GET_NEW_OPERATIONS_SUCCESS = 'REQUEST_GET_NEW_OPERATIONS_SUCCESS';
export const REQUEST_GET_OPERATION_SUCCESS = 'REQUEST_GET_OPERATION_SUCCESS';


export const REQUEST_GET_REGION_BY_COUNTRY_SUCCESS = 'REQUEST_GET_REGION_BY_COUNTRY_SUCCESS';
export const REQUEST_GET_DISTRICT_BY_REGION_SUCCESS = 'REQUEST_GET_DISTRICT_BY_REGION_SUCCESS';

export const REQUEST_ATTACHMENT_SUCCESS = 'REQUEST_ATTACHMENT_SUCCESS';
export const REQUEST_ATTACHMENT_LIST_SUCCESS = "REQUEST_ATTACHMENT_LIST_SUCCESS";
export const REQUEST_SOCIAL_ENUM_SUCCESS = 'REQUEST_SOCIAL_ENUM_SUCCESS';
export const REQUEST_GET_SECTION_SUCCESS = 'REQUEST_GET_SECTION_SUCCESS';
export const REQUEST_GET_REGION_SUCCESS = 'REQUEST_GET_REGION_SUCCESS';
export const REQUEST_GET_DISTRICT_SUCCESS = 'REQUEST_GET_DISTRICT_SUCCESS';
export const REQUEST_GET_ORDER_SUCCESS = 'REQUEST_GET_ORDER_SUCCESS';